### ISSUE TITLE
[Bug Report] growth command fails to show in help or work on updated version

### ISSUE THREAD

**Issue by WhoTheOOF** [dragdev-studios/guildmanager#15]
the title explains it all @EEKIM10 

growth command fails to show in help or work on updated version after guildmanager.data was deleted and bot restarted and reloaded

**Comment by EEKIM10** [comment]
guildmanager.data shouldn't affect this since it doesn't mess with it

I'll look into this.

**Comment by EEKIM10** [comment]
upon further inspection i can't reproduce this and if you look at the code, there's no reason it shouldn't show up as the only check is the is_owner cog check.

And since this issue wasn't filled out in the proper format i will label it as invalid and close.

Feel free to open a new issue with the correct format and details if the issue persists.
